<<<<<<< HEAD
title: Programiranje 1
author: Matija Pretnar
exclude_patterns:
  - odlozisce/*
repository:
  url: 'https://github.com/matijapretnar/programiranje-1'
  book_path: zapiski
  branch: zapiski
launch_buttons:
  binderhub_url: 'https://mybinder.org'
=======
title: Programiranje 1
author: Matija Pretnar
exclude_patterns:
  - odlozisce/*
repository:
  url: 'https://github.com/matijapretnar/programiranje-1'
  book_path: zapiski
  branch: zapiski
only_build_toc_files: true
execute:
  exclude_patterns:
    - 'dn-*.ipynb'
>>>>>>> cb539d17af9b0e6c7df5ce1b0e6e44b2681a46bf
